DLSV2-517 Include NominatedSupervisors in the Manage Supervisors pick supervisor list
TechnologyEnhancedLearning/DLSV2 pull request #1012
Opened 2022-03-11 14:08 UTC by daniel-manta-hee

Include NominatedSupervisors in the Manage Supervisors pick supervisor list

### JIRA link
https://hee-dls.atlassian.net/browse/DLSV2-517

### Description
Updated query in SelfAssessmentSupervisorDataService.cs for including nominated supervisors in "activity supervisors" list and active admins in "quick add". 

Also generated RoleName in the query. Not sure if that's needed. Despite `RoleName` had a hardcoded "Supervisor" value in the original code, it seems ManageSupervisors.cshtml displays `supervisor.RoleName` from table SelfAssessmentSupervisorRoles.

### Screenshots
![image](https://user-images.githubusercontent.com/94055251/157883114-dfbb6a3b-c1a4-4e7c-b7ab-a78023496612.png)

-----
### Developer checks
Checked that nominated supervisors are included on the "activity supervisors" list.

2022-03-22 15:40 UTC, kevwhitt-hee requested changes
one minor change requested in comments

2022-03-23 16:20 UTC, daniel-manta-hee commented on DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
> +		                 ELSE 'Learner'
Change implemented and committed.

2022-03-24 17:11 UTC, kevwhitt-hee commented
Please resolve conflicts in the data service.

2022-03-29 07:40 UTC, kevwhitt-hee approved these changes

2022-03-29 07:41 UTC, merged