Heedls 607 course delegates export all
TechnologyEnhancedLearning/DLSV2 pull request #1013
Opened 2022-03-11 15:38 UTC by AlexJacksonDS

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-607

### Description
Added the Export All excel download to the Delegate Courses page. This outputs an excel file for all delegates on the currently displayed courses.

Note that this should make use of the new search/sort/filter service so, depending on what gets merged first, that change needs to be made.

### Screenshots
![image](https://user-images.githubusercontent.com/59561751/157897369-f1c1407b-0425-4a48-8b39-77763953fdb5.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2022-03-11 16:25 UTC, GeorgeBlackwell requested changes
Nice work, just a few minor comments

2022-03-11 16:25 UTC, GeorgeBlackwell commented on DigitalLearningSolutions.Data.Tests/Services/CourseDelegatesDownloadFileServiceTests.cs
> +        public const string CourseDelegateExportAllDataDownloadRelativeFilePath =
Do these need to be public?

2022-03-11 16:25 UTC, GeorgeBlackwell commented on DigitalLearningSolutions.Web/Scripts/trackingSystem/delegateCourses.ts
> +  exportAllLink.href = pathWithCurrentSortFilter;
You could get away with assigning `exportAllLink.href` directly here

2022-03-11 17:38 UTC, JBsoftwire requested changes
Looks good, but I think the filename might create problems for users.

2022-03-11 17:38 UTC, JBsoftwire commented on DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs
> +            const string fileName = "Digital Learning Solutions Course Delegates.xlsx";
Unless this filename has been specified I think it wants some kind of identifying detail, for example the datetime. Right now there'll be no way to distinguish different downloads.

2022-03-14 11:03 UTC, GeorgeBlackwell approved these changes
Nice work!

2022-03-14 11:16 UTC, merged