UAR-830 Create Users table
TechnologyEnhancedLearning/DLSV2 pull request #1019
Opened 2022-03-15 16:36 UTC by livzorn

### JIRA link
_HEEDLS-830_

### Description
Create a new Users table for the user accounts refactor

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [x] Scanned over my own MR to ensure everything is as expected.

2022-03-16 08:22 UTC, DanBloxham-sw requested changes
Looks decent, just Alex's comments to check up one.

2022-03-16 08:22 UTC, DanBloxham-sw commented on DigitalLearningSolutions.Data.Migrations/202203151032_AddUsersTable.cs
> +                .WithColumn("PasswordHash").AsString(70).NotNullable()
I think the hashed passwords always come out at the same length. I had a quick check on some randomly selected records and they all seem to be 68 characters.

2022-03-16 09:30 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data.Migrations/202203151032_AddUsersTable.cs
> +                .WithColumn("PasswordHash").AsString(70).NotNullable()
Good point Alex.Yeah, I think so too Dan. 70 should be fine.

2022-03-16 09:42 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data.Migrations/202203151032_AddUsersTable.cs
> +                .WithColumn("LastName").AsString(100).NotNullable()
Good point. Just asked Kevin how precious he is about this length change.

2022-03-16 16:53 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data.Migrations/202203151032_AddUsersTable.cs
> +                .WithColumn("LastName").AsString(100).NotNullable()
Kevin says sticking with 250 is fine because it seems like it'll be simpler.

2022-03-17 09:19 UTC, livzorn commented on DigitalLearningSolutions.Data.Migrations/202203151032_AddUsersTable.cs
> +                .WithColumn("LastName").AsString(100).NotNullable()
changed to 250

2022-03-17 09:23 UTC, AlexJacksonDS approved these changes

2022-03-17 09:43 UTC, merged