HEEDLS-778 : Update export button and hint
TechnologyEnhancedLearning/DLSV2 pull request #1024
Opened 2022-03-18 11:06 UTC by GeorgeBlackwell

### JIRA link
_[HEEDLS-778](https://softwiretech.atlassian.net/browse/HEEDLS-778)_

### Description
_Updated the export button and hint on the course delegates page._

### Screenshots
![image](https://user-images.githubusercontent.com/58184056/158992014-52b0afa2-84d7-4e36-829b-5d27a49fadf5.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [X] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [X] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [X] Scanned over my own MR to ensure everything is as expected.

2022-03-18 11:20 UTC, livzorn requested changes

2022-03-18 11:20 UTC, livzorn commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/Index.cshtml
> +            Choose a course to see delegates enrolled on it. If you'd like to export delegates on all courses, click "Export" above.
I think we can remove this entire second sentence, since it refers to the button that's no longer on this page?

2022-03-18 16:15 UTC, AlexJacksonDS requested changes
Possible extra change to tidy up, and I'm not sure the correct change has been made for the previous review

2022-03-18 16:15 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/Index.cshtml
> -      </div>
I'm not sure this was what Olivia meant, only to remove "If you'd like to export delegates on all courses, click "Export all" above."

2022-03-18 16:15 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/Index.cshtml
>               asp-route-sortDirection="@Model.CourseDetails?.SortDirection"
Can't comment it against the line, but I think we should probably update the id & the corresponding javascript that uses it now that the button is not Export Current

2022-03-21 09:27 UTC, AlexJacksonDS approved these changes
Looks good to me

2022-03-21 09:49 UTC, merged