HEEDLS-621 - fix course delegates URL and Staff List return pages
TechnologyEnhancedLearning/DLSV2 pull request #1030
Opened 2022-03-22 12:50 UTC by DanBloxham-sw

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-621

### Description
Fixed the Staff List return page issue for the removal confirmation page, but the link to the page is strangely set up and will point to a bad action when the user has no self assessments.
Fixed the course delegates page by modifying the JS to take query in a whitelisted query parameter and preserve any that match. 
Have not been able to fix the screen reader issue. 

### Screenshots
N/A

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2022-03-22 14:41 UTC, GeorgeBlackwell requested changes
Nice work 🚀 Just a minor comment

2022-03-22 14:41 UTC, GeorgeBlackwell commented on DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/searchSortFilterAndPaginate.ts
> +  private queryParameterToRetain: string;
You could make this `readonly`

2022-03-22 15:52 UTC, AlexJacksonDS reviewed
Looks OK to me, just the other comment to resolve

2022-03-23 09:25 UTC, AlexJacksonDS approved these changes

2022-03-23 09:56 UTC, merged