Heedls 869 brand details
TechnologyEnhancedLearning/DLSV2 pull request #1064
Opened 2022-04-08 12:49 UTC by tangboxuan

### JIRA Link
(_HEEDLS-869_)[https://softwiretech.atlassian.net/browse/HEEDLS-869]

### Description
_Each brand page now displays the Brand Name and Brand Description (if the brand is publicly visible), instead of having a iframe pointing to the legacy version._

### Screenshots
![localhost_5001_LearningContent_1](https://user-images.githubusercontent.com/67381570/162438646-8492c5f4-f386-4f0c-8cde-3377e69a2899.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [X] Run the formatter and made sure there are no IDE errors.
- [X] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [X] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [X] Scanned over my own MR to ensure everything is as expected.

2022-04-08 15:02 UTC, DanBloxham-sw requested changes
Looks good overall, I've left a number of comments on some relatively minor things I think can be changed. Not sure how much this will overlap with 864.

2022-04-08 15:32 UTC, tangboxuan commented on DigitalLearningSolutions.Web/Controllers/LearningContentController.cs
> +            var model = new LearningContentViewModel(brand);
This was the original ViewModel name. Should we rename it?

2022-04-11 10:17 UTC, tangboxuan commented
Changes to be made in 870:
1. New products.scss file to define custom classes to replace classes in LearningContent/Index.cshtml
2.

2022-04-11 11:33 UTC, tangboxuan commented on DigitalLearningSolutions.Web/Controllers/LearningContentController.cs
> +            var model = new LearningContentViewModel(brand);
we will be adding more fields into the LearningContentViewModel (to carry the list of tutorials and courses to also be displayed)

2022-04-11 14:05 UTC, livzorn requested changes
Looking good, just some minor points to look at

2022-04-11 14:05 UTC, livzorn commented on DigitalLearningSolutions.Web/Controllers/LearningContentController.cs
>              return View("Index", model);
If you change this controller action name to "Index", you should be able to remove the View name "Index" from this line :)

2022-04-11 14:05 UTC, livzorn commented on DigitalLearningSolutions.Web/Views/LearningContent/Index.cshtml
>  ﻿@using DigitalLearningSolutions.Data.Extensions
unused import

2022-04-11 14:06 UTC, livzorn commented on DigitalLearningSolutions.Web/Controllers/LearningContentController.cs
> +        public IActionResult BrandPageDeliveryService(int brandId)
This would also involve changing some test names and the action in the button

2022-04-12 09:04 UTC, livzorn requested changes

2022-04-12 15:10 UTC, livzorn commented on DigitalLearningSolutions.Data/DataServices/BrandsDataService.cs
>                      BrandID,
This indentation is not messed up locally for both Boxuan and I, not sure why but we'll leave it be for now

2022-04-12 15:45 UTC, merged