HEEDLS-861 - add additional pagination controls at top of lists
TechnologyEnhancedLearning/DLSV2 pull request #1070
Opened 2022-04-13 13:55 UTC by DanBloxham-sw

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-861

### Description
Created a new pagination configuration that can be placed at the top of lists to provide an additional set of pagination controls. I've had to refactor the pagination JS/views to allow the set up to work with multiple sets of pagination controls. 

Changed the ellipsis in the loading page warning to a full stop.

Mysteriously, the announcement of page numbers and result count seems to work as we would hope without any modifications (at least in Chrome). Even on the test site. So I have no changed anything for that, and we will have to see if we have any problems when this is tested.

### Screenshots
Example page of All Delegates

Desktop:
![All delegates desktop](https://user-images.githubusercontent.com/80777689/163196258-a43f073b-7f40-4444-aada-c4946ad40431.png)

Tablet
<img src="https://user-images.githubusercontent.com/80777689/163196281-bd95278b-41f0-41a4-ab54-75031150a06e.png" width=768px />

Mobile
<img src="https://user-images.githubusercontent.com/80777689/163196206-2737e647-fbff-4d71-b64a-ea1ac67cff3a.png" width=320px />

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2022-04-13 14:12 UTC, DanBloxham-sw commented on DigitalLearningSolutions.Web/Views/Shared/PaginatedPage/_BaseConfigurablePaginationNav.cshtml
> +        <span class="page-indicator" @(Model.pageModel.TotalPages <= 1 ? "hidden" : "")>@Model.pageModel.Page of @Model.pageModel.TotalPages</span>
I've added the logic to hide this when there is 1 or 0 pages to fix the bug from 881.

2022-04-13 14:32 UTC, AlexJacksonDS requested changes
Changes overall look fine to me, just one issue with naming.

I also wonder if we should try to decrease this spacing on the top controls?
![image](https://user-images.githubusercontent.com/59561751/163204129-9a68c919-ff32-4e65-8b66-2d45dd53db06.png)

2022-04-13 14:32 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_PaginationInputs.cshtml
> +﻿@using DigitalLearningSolutions.Web.ViewModels.Common.SearchablePage
I think this probably needs a different name, this implies to me it is the inputs that are required for the pagination functionality, not the other inputs for the rest of the stuff.

2022-04-14 11:54 UTC, GeorgeBlackwell requested changes
Nice work, just a minor comment

2022-04-14 11:54 UTC, GeorgeBlackwell commented on DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/paginate.ts
> +    element.hidden = page === 1;
You can inline this and remove the need for `element`

2022-04-14 14:54 UTC, DanBloxham-sw commented
After the Show and Tell today (14th April 2022) it was decided that the current spacing was fine, so I'll not change any of that around.

2022-04-14 15:41 UTC, GeorgeBlackwell approved these changes

2022-04-19 07:10 UTC, merged