Code Fix
TechnologyEnhancedLearning/DLSV2 pull request #1101
Opened 2022-05-06 15:22 UTC by Prasanna-Nadella

Code Fix

### https://hee-dls.atlassian.net/browse/DLSV2-510
_HEEDLS-XXXX_

### Description
_Describe what has changed and how that will affect the app. If relevant, add references to the resources you used. Use this as your opportunity to highlight anything odd and give people context around particular decisions._

### Screenshots
_Attach screenshots on mobile, tablet and desktop._

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [x ] Scanned over my own MR to ensure everything is as expected.

2022-05-06 15:57 UTC, kevwhitt-hee reviewed
Looks good. One slight tweak required - see code comments.

2022-05-06 15:57 UTC, kevwhitt-hee commented on DigitalLearningSolutions.Data/Services/CandidateAssessmentDownloadFileService.cs
> +            sheet.Cell(rowNum, 2).Value = (!string.IsNullOrEmpty(candidateAssessmentExportSummary.CandidatePrn) ? "Recorded" : "Not Recorded");
We want to show the candidates PRN if present, so this line should be something like:
`sheet.Cell(rowNum, 2).Value = (!string.IsNullOrEmpty(candidateAssessmentExportSummary.CandidatePrn) ? candidateAssessmentExportSummary.CandidatePrn.ToString() : "Not Recorded");`

2022-05-06 15:57 UTC, kevwhitt-hee requested changes
Looks good. One slight tweak required - see code comments.

2022-05-06 16:11 UTC, Prasanna-Nadella commented
But the issue says differently. Below is the exact wording from DLSV2-510. Please confirm if you still would like to replace "Recorded" with the PRN.


In both places, we should replace this with “Recorded” if a PRN exists and “Not Recorded” if it is blank.


Thanks & Regards
________________________________
From: kevwhitt-hee ***@***.***>
Sent: 06 May 2022 16:57
To: TechnologyEnhancedLearning/DLSV2 ***@***.***>
Cc: Prasanna Nadella ***@***.***>; Author ***@***.***>
Subject: Re: [TechnologyEnhancedLearning/DLSV2] DLSV2-510 Fix to PRN display in Self Assessment Excel Export (PR #1101)


@kevwhitt-hee commented on this pull request.

Looks good. One slight tweak required - see code comments.

________________________________

In DigitalLearningSolutions.Data/Services/CandidateAssessmentDownloadFileService.cs<https://github.com/TechnologyEnhancedLearning/DLSV2/pull/1101#discussion_r866945204>:

> @@ -70,7 +70,7 @@ private static void AddSummarySheet(IXLWorkbook workbook, CandidateAssessmentExp
             rowNum++;
             sheet.Cell(rowNum, 1).Value ="Learner PRN";
             sheet.Cell(rowNum, 1).Style.Fill.BackgroundColor = XLColor.LightBlue;
-            sheet.Cell(rowNum, 2).Value = candidateAssessmentExportSummary.CandidatePrn;
+            sheet.Cell(rowNum, 2).Value = (!string.IsNullOrEmpty(candidateAssessmentExportSummary.CandidatePrn) ? "Recorded" : "Not Recorded");


We want to show the candidates PRN if present, so this line should be something like:
sheet.Cell(rowNum, 2).Value = (!string.IsNullOrEmpty(candidateAssessmentExportSummary.CandidatePrn) ? candidateAssessmentExportSummary.CandidatePrn.ToString() : "Not Recorded");

—
Reply to this email directly, view it on GitHub<https://github.com/TechnologyEnhancedLearning/DLSV2/pull/1101#pullrequestreview-964824980>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYS2IRTGH2OLHCRG2PAQLBTVIU6OPANCNFSM5VIPPBYA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

This message may contain confidential information. If you are not the intended recipient, please inform the sender that you have received the message in error before deleting it. If the email was not meant for you, please do not disclose, copy or distribute the information it contains or take any action based on its contents, apart from notifying the sender you have received it in error. Any other action is prohibited and may be unlawful.

Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

This email has been scanned for viruses and malware, and may have been automatically archived by Mimecast Ltd, an innovator in Software as a Service (SaaS) for business. Providing a safer and more useful place for your human generated data. Specializing in; Security, archiving and compliance. To find out more visit the Mimecast website.

2022-05-06 16:17 UTC, kevwhitt-hee commented
The "both places" comment relates to both places where supervisor PRN is currently displayed. Because this is the learner PRN, we should display the actual PRN for the learner if it exists but for the sake of consistency, we should show "Not recorded" if it doesn't.

2022-05-09 08:36 UTC, Prasanna-Nadella commented
Hi Kevin,

Good morning.

That makes sense and it's done now.

Checked-in and pushed the changes as well.

Please check it and let me know if anything else is required?

Best Regarads

________________________________
From: kevwhitt-hee ***@***.***>
Sent: 06 May 2022 17:18
To: TechnologyEnhancedLearning/DLSV2 ***@***.***>
Cc: Prasanna Nadella ***@***.***>; Author ***@***.***>
Subject: Re: [TechnologyEnhancedLearning/DLSV2] DLSV2-510 Fix to PRN display in Self Assessment Excel Export (PR #1101)


The "both places" comment relates to both places where supervisor PRN is currently displayed. Because this is the learner PRN, we should display the actual PRN for the learner if it exists but for the sake of consistency, we should show "Not recorded" if it doesn't.

—
Reply to this email directly, view it on GitHub<https://github.com/TechnologyEnhancedLearning/DLSV2/pull/1101#issuecomment-1119783720>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYS2IRXDHVRFV7FHD7KHS7DVIVA3TANCNFSM5VIPPBYA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

This message may contain confidential information. If you are not the intended recipient, please inform the sender that you have received the message in error before deleting it. If the email was not meant for you, please do not disclose, copy or distribute the information it contains or take any action based on its contents, apart from notifying the sender you have received it in error. Any other action is prohibited and may be unlawful.

Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

This email has been scanned for viruses and malware, and may have been automatically archived by Mimecast Ltd, an innovator in Software as a Service (SaaS) for business. Providing a safer and more useful place for your human generated data. Specializing in; Security, archiving and compliance. To find out more visit the Mimecast website.

2022-05-09 10:49 UTC, kevwhitt-hee requested changes
Noticed a small issue in the details tab. When a result hasn't been confirmed, we still show "Not recorded" in the PRN column, even though there is no reviewer in the reviewer column:
![image](https://user-images.githubusercontent.com/67740339/167395264-2d48c3c1-12a4-4d1c-b5c5-07b57c9ae318.png)
We should leave the field blank if the result hasn't been confirmed (i.e. if the Reviewer column is blank).

2022-05-09 11:52 UTC, Prasanna-Nadella commented
Amended it by adding Reviewer check to the query.

Please check the attached O/P file and let me know.

Thanks

________________________________
From: kevwhitt-hee ***@***.***>
Sent: 09 May 2022 11:49
To: TechnologyEnhancedLearning/DLSV2 ***@***.***>
Cc: Prasanna Nadella ***@***.***>; Author ***@***.***>
Subject: Re: [TechnologyEnhancedLearning/DLSV2] DLSV2-510 Fix to PRN display in Self Assessment Excel Export (PR #1101)


@kevwhitt-hee requested changes on this pull request.

Noticed a small issue in the details tab. When a result hasn't been confirmed, we still show "Not recorded" in the PRN column, even though there is no reviewer in the reviewer column:
[image]<https://user-images.githubusercontent.com/67740339/167395264-2d48c3c1-12a4-4d1c-b5c5-07b57c9ae318.png>
We should leave the field blank if the result hasn't been confirmed (i.e. if the Reviewer column is blank).

—
Reply to this email directly, view it on GitHub<https://github.com/TechnologyEnhancedLearning/DLSV2/pull/1101#pullrequestreview-965941116>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYS2IRQSK2J4HUJTH42TDA3VJDUURANCNFSM5VIPPBYA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

This message may contain confidential information. If you are not the intended recipient, please inform the sender that you have received the message in error before deleting it. If the email was not meant for you, please do not disclose, copy or distribute the information it contains or take any action based on its contents, apart from notifying the sender you have received it in error. Any other action is prohibited and may be unlawful.

Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

This email has been scanned for viruses and malware, and may have been automatically archived by Mimecast Ltd, an innovator in Software as a Service (SaaS) for business. Providing a safer and more useful place for your human generated data. Specializing in; Security, archiving and compliance. To find out more visit the Mimecast website.

2022-05-11 07:23 UTC, kevwhitt-hee approved these changes
All good.

2022-05-11 07:23 UTC, merged