Uar 882 admin category id nullable
TechnologyEnhancedLearning/DLSV2 pull request #1111
Opened 2022-05-13 13:02 UTC by AlexJacksonDS

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-882

### Description
Changed AdminUser.CategoryId to nullable, and updated usages of it. I expect there to be some minor conflicts with other in progress tickets.

### Screenshots
N/A

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2022-05-13 13:06 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Data/DataServices/EvaluationSummaryDataService.cs
> -					    SUM(CASE WHEN Q1 = 0 THEN 1 ELSE 0 END) AS Q1No,
This is just tabs to spaces I noticed as I was checking for categoryIds

2022-05-18 11:17 UTC, SteveJacksonSoft requested changes

2022-05-18 11:17 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Web/Models/AdminLoginDetails.cs
> +            CategoryId = adminUser.CategoryId ?? 0;
It'd be nice to extract this into a helper method for mapping `AdminCategory => CategoryId` and do the same for `CategoryId => AdminCategory`, then use those methods everywhere we convert between the two. Then it's possible to find everywhere we're doing the conversion by looking for usages of those methods.

2022-05-19 13:11 UTC, GeorgeBlackwell reviewed
Looks good, nothing to add beyond Steve's helper suggestion

2022-05-19 14:52 UTC, GeorgeBlackwell approved these changes

2022-05-19 14:57 UTC, merged