Uar 898 fix login
TechnologyEnhancedLearning/DLSV2 pull request #1122
Opened 2022-05-17 15:58 UTC by AlexJacksonDS

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-898

### Description
Fixed the login process so that it works with the new account system. 
Fixed the UI tests so that it logs into an account correctly and they run. This requires a small script running SQLScripts/UpdateCandidateAssessmentsAndDelegateAccountOldPasswordForUITests.sql

Since we also have a number of changes to the Choose a Centre page to come, this page currently doesn't work correctly, so I've added a placeholder journey so that it is possible to get into an account associated with the login if necessary, and allow it to be obvious during testing that the redirects to the Choose a Centre page are working as expected. This will default to an available admin account. I've stuck this very obvious large button that should get removed when the Choose a centre page is fixed:
![image](https://user-images.githubusercontent.com/59561751/168848885-10092aa6-5e87-4ecd-b411-a44b817ffe2e.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2022-05-19 17:14 UTC, SteveJacksonSoft requested changes
Haven't looked through the tests yet, but I've gone through the rest. I'll leave these comments to avoid blocking you further.

2022-05-19 17:14 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data/Models/User/UserEntity.cs
> +        public bool AdminAccountsLocked => UserAccount.FailedLoginCount >= FailedLoginThreshold;
Sorry, this name isn't quite as sensible as it was when we were only locking admin accounts.
Probably more useful to have an `IsLocked` property `= UserAccount.FailedLoginCount >= FailedLoginThreshold && AdminAccounts.Any()`.

2022-05-19 17:14 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data/Models/User/CentreUserDetails.cs
>      public class CentreUserDetails
Can we rename this? It's disturbingly close to UserCentreDetails. Something like ChooseACentreAccount...?

2022-05-19 17:14 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
> +                    INNER JOIN DelegateAccounts AS da ON da.UserID = u.ID
Think you want left join - there may be users with no delegate accounts.

2022-05-20 08:17 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/Controllers/LoginController.cs
> +                    return View("AccountLocked", loginResult.UserEntity!.UserAccount.FailedLoginCount + 1 );
Which fixes exactly? The wording change from the view and the reset password behaviour won't be there yet as it's not yet merged. The logic for preventing login from a locked account is unneeded, as it should be replaced by new matching logic.

2022-05-20 08:26 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Data/Services/LoginService.cs
> +            var adminAccountIsAtSingleCentreAndIsLocked =
I don't think it is actually possible to get to this case any more with the Account Locked logic above?

2022-05-20 10:05 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Web/Controllers/LoginController.cs
> +                    return View("AccountLocked", loginResult.UserEntity!.UserAccount.FailedLoginCount + 1 );
Oh, it was an edge case that resulted in the AccountLocked page saying the user has had 6 incorrect logins when they've actually only had 5... here it is in slack: https://softwire.slack.com/archives/C01D7RQFF2P/p1652263537367209?thread_ts=1652169386.948529&cid=C01D7RQFF2P

2022-05-20 10:06 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data/Services/LoginService.cs
> +            var singleCentreToLogUserInto = GetCentreIdIfLoggingUserIntoSingleCentre(userEntity, username);
Oh, the ResetFailedLoginCount should maybe go in here too

2022-05-20 10:08 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data/Services/LoginService.cs
> +            var adminAccountIsAtSingleCentreAndIsLocked =
Pretty sure that a valid username and password combination for a locked user account will reach this line. The only place an `AccountLocked` login result is being returned is in an `if (!passwordMatchesAtLeastOneAccount)` statement

2022-05-20 12:00 UTC, GeorgeBlackwell reviewed
Just a few comments on top of Steve's

2022-05-20 12:00 UTC, GeorgeBlackwell commented on DigitalLearningSolutions.Web.IntegrationTests/TestHelpers/TestUserDataService.cs
>      public class TestUserDataService
Should probably make the whole class `static`

2022-05-20 14:02 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Data/Services/UserService.cs
> +            }
After removing the thrown exception, this will go to the Choose A Centre page

2022-05-20 14:03 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Data/Services/LoginService.cs
> +            var adminAccountIsAtSingleCentreAndIsLocked =
I've shuffled around the logic, so if the user entity is locked before reaching the new DetermineDestinationForSuccessfulLoginAttempt() method, it'll return the locked result

2022-05-20 15:49 UTC, GeorgeBlackwell approved these changes
Looks good!

2022-05-20 16:02 UTC, merged