HEEDLS-886 fix screen reader text, email storage, email validation
TechnologyEnhancedLearning/DLSV2 pull request #1163
Opened 2022-06-01 14:33 UTC by JBsoftwire

### JIRA link
_[HEEDLS-886](https://softwiretech.atlassian.net/browse/HEEDLS-886)_

### Description
- Removed obsolete validation-execution conditions from email validation.
- Corrected validation messages.
- Added filling of centre email on return to Personal Information page.
- Corrected screen reader text.

### Screenshots
N/A (no change)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [x] Scanned over my own MR to ensure everything is as expected.

2022-06-06 08:22 UTC, AlexJacksonDS requested changes
Overall looks fine, just one comment about duplicating strings

2022-06-06 08:22 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs
> +                    "A user with this email address is already registered; if this is you, please log in at this centre via the My Account page"
The 2 message strings are the same, probably worth pulling them into a const

2022-06-06 13:48 UTC, livzorn reviewed
Looks good! Nothing to add beyond Alex's comment

2022-06-07 10:49 UTC, livzorn approved these changes

2022-06-07 10:59 UTC, merged