Develop/fixes/dlsv2 656 text area height no js 2
TechnologyEnhancedLearning/DLSV2 pull request #1400
Opened 2022-09-20 10:09 UTC by martinfoster-hee

### JIRA link
https://hee-dls.atlassian.net/jira/software/projects/DLSV2/boards/1?selectedIssue=DLSV2-656

### Description
Swapped the standard textarea controls to use textarea view component. This now correctly renders a 5 row textarea when javascript is disabled in the browser (with js enabled the control still renders as a textarea with the html-editor functionality).

The new control appears on the following four pages:
AssessmentQuestionsOptions.cshtml
Description.cshtml
Competency.cshtml
CompetencyGroup.cshtml

### Screenshots
See attached.

-----
### Developer checks
I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [x] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [x] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [x] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [x] Scanned over my own MR to ensure everything is as expected and it looks right in the browser

![final_assessement_outcome_js_desktop](https://user-images.githubusercontent.com/113513647/191230598-435d66a9-a74c-4717-aff4-73d5f14a6e24.png)
![final_assessement_outcome_nojs_desktop](https://user-images.githubusercontent.com/113513647/191230603-955988bc-0395-4fd4-93ab-e8fd343db76e.png)
![edit_competency_group_js_desktop](https://user-images.githubusercontent.com/113513647/191230608-83911647-81ed-4621-bbfb-bd97d20d2829.png)
![edit_competency_group_nojs_desktop](https://user-images.githubusercontent.com/113513647/191230612-9329d71d-fcdf-4310-becf-b5f5228f6bce.png)
![edit_competency_js_desktop](https://user-images.githubusercontent.com/113513647/191230619-33aaa169-5e13-4850-8613-119c23a0bd9c.png)
![edit_competency_nojs_desktop](https://user-images.githubusercontent.com/113513647/191230622-95a68a43-7dc3-4e48-9ac1-543b332e8e4e.png)
![edit_framework_description_js_desktop](https://user-images.githubusercontent.com/113513647/191230624-e85f8f20-ca19-4f16-9715-a87c2e0e1218.png)
![edit_framework_description_nojs_desktop](https://user-images.githubusercontent.com/113513647/191230628-957d8bfb-46f7-406b-95e5-0b091c025228.png)

2022-09-20 14:00 UTC, kevwhitt-hee requested changes
This is working well when I run it in dev. See comment about moving value to set functions out to a helper class. This would allow us to call them from other view components if we face the same problem.

2022-09-20 14:07 UTC, martinfoster-hee commented on DigitalLearningSolutions.Web/ViewComponents/TextAreaViewComponent.cs
> +        private string ValueToSetForSimpleType(object model, string aspFor, bool populateWithCurrentValue, out IEnumerable<string> errorMessages)
Yes good idea - we are likely to need this for refactoring other types of view components where we have complex view models.

2022-09-21 10:27 UTC, martinfoster-hee commented on DigitalLearningSolutions.Web/ViewComponents/TextAreaViewComponent.cs
> +        private string ValueToSetForSimpleType(object model, string aspFor, bool populateWithCurrentValue, out IEnumerable<string> errorMessages)
@kevwhitt-hee I've refactored the two model binding functions to a helper class as requested. 

I've also refactored the main calling function which decides which of the two methods to call as that will reduce code simplify the calls in the controllers (although the controllers can still call the other two functions directly if needed).

2022-09-22 06:48 UTC, kevwhitt-hee approved these changes
Looks good. Tests for the helper are a good addition too.

2022-09-22 06:48 UTC, merged