Develop/fixes/dlsv2 609 issue with the mismatch of the field names in mobile view compared to desktop view when viewing proficiency on the self assessment page
TechnologyEnhancedLearning/DLSV2 pull request #1408
Opened 2022-09-28 14:04 UTC by OluwatobiAwe

### JIRA link
https://hee-dls.atlassian.net/browse/DLSV2-609

### Description
Responsive header text updated to reflect the same content as desktop view. 
The **Action** column is hidden on Desktop View, but visible on the mobile view to aid usability.

### Screenshots
![DesktopCapture](https://user-images.githubusercontent.com/114475132/192795757-c25e10b6-00eb-4de3-89f4-f20bef7fbcb5.PNG)
![MobileCapture](https://user-images.githubusercontent.com/114475132/192795762-d8519d22-219b-4c78-802b-74f568d1e384.PNG)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [x] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [x] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [x] Scanned over my own MR to ensure everything is as expected and it looks right in the browser

2022-09-28 14:38 UTC, kevwhitt-hee requested changes
This looks good, Oluwatobi. Could we also look to fix the issue with the alignment of the Competency item:
![image](https://user-images.githubusercontent.com/67740339/192808178-8411ef80-d108-4ac0-bf92-37d8c8500659.png)
It seems to switch to right aligned when the text is too long. Could we move it to the left (or work out why it's moving)?

2022-09-29 12:32 UTC, OluwatobiAwe commented
The nhsuk base CSS stylesheet targetting tables in mobile views, aligns content to the right. I then added the style to the self-accessment style sheet to reflect the expected behavior only on that page. I did this by adding the text-align property to left.

![MobileViewUpdate](https://user-images.githubusercontent.com/114475132/193030424-86259c84-cdd5-4ad6-97b6-94bcb26b4f99.PNG)

2022-09-30 07:43 UTC, kevwhitt-hee reviewed
I could see a way to fix the alignment problem without the CSS change. This works better with the flags that aren't visible on your screenshot (none of the competencies are flagged in the DB).

2022-09-30 07:43 UTC, kevwhitt-hee commented on DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml
> +          <span class="nhsuk-table-responsive__heading">@competency.Vocabulary </span>
I've moved this outside of the details expander and this seems to have fixed the alignment and made it consistent with the other items in the summary without CSS changes.

2022-09-30 07:45 UTC, merged