Develop/Fixes/TD-707_DelegateCoursesArchivedUIElements
TechnologyEnhancedLearning/DLSV2 pull request #1493
Opened 2022-11-30 12:32 UTC by martinfoster-hee

### JIRA link
_DLSV2-XXXX_

### Description
_Describe what has changed and how that will affect the app. If relevant, add references to the resources you used. Use this as your opportunity to highlight anything odd and give people context around particular decisions._

### Screenshots
_Attach screenshots on mobile, tablet and desktop._

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

2022-12-01 08:13 UTC, kevwhitt-hee requested changes
Changes look good and work well when built. Having reviewed the built application, though, I think we need to tweak the status filter slightly:
- Applying an 'Active' filter should display only active courses that have not been archived.
- Applying an 'Inactive' filter should display courses that are inactive or archived.
- We should rename the 'Inactive' filter option as 'Inactive/archived'.

2022-12-06 15:21 UTC, kevwhitt-hee commented
@martinfoster-hee just a nudge to remind you of the requested changes on this one.

2022-12-15 12:00 UTC, martinfoster-hee commented
Updated filters are requested.

2022-12-16 08:35 UTC, kevwhitt-hee approved these changes

2022-12-16 08:36 UTC, merged