merge issue for double execution CreateNewDelegateProgress() resolved…
TechnologyEnhancedLearning/DLSV2 pull request #1579
Opened 2023-01-20 14:32 UTC by Auldrin-Possa

**JIRA link**

**Description**
merge issue for double execution CreateNewDelegateProgress() resolved. links are updated to the completed menu.

**Screenshots**
Updated in Jira ticket.

-----
**Developer checks**

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [x] Tested any Views or partials created or changed with [Wave Chrome plugin]
- [ ] Updated/added documentation in [Confluence]
- [x] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [x] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

2023-01-20 14:56 UTC, martinfoster-hee commented on DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs
>                  enrolService.EnrolDelegateOnCourse(delegateId, sessionEnrol.AssessmentID.GetValueOrDefault(), sessionEnrol.AssessmentVersion, 0, GetAdminID(), sessionEnrol.CompleteByDate, sessionEnro
Was this the duplicate call? Just curious! (Deleting existing code makes me anxious lol).

2023-01-20 15:00 UTC, kevwhitt-hee requested changes
I think the changes to return to the Completed activities view all need reverting @Auldrin-Possa , unless they do something I don't understand?

2023-01-20 15:29 UTC, Auldrin-Possa commented on DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
> +            return RedirectToAction("Completed", "LearningPortal");
links are used in the completed section and working correctly.

2023-01-20 15:38 UTC, kevwhitt-hee commented on DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs
> -                progressDataService.CreateNewDelegateProgress(delegateId, sessionEnrol.AssessmentID.GetValueOrDefault(), sessionEnrol.AssessmentVersion,
This code is needed. Please revert this change. We will need to set up and poulate delegateId variable above to pass into it, too.

2023-01-23 08:01 UTC, Auldrin-Possa commented
> 



> I think the changes to return to the Completed activities view all need reverting @Auldrin-Possa , unless they do something I don't understand?

Reverted.

2023-01-23 08:06 UTC, kevwhitt-hee commented
Morning @Auldrin-Possa, there is a build fail on this branch now. Please could you look into fixing it?

2023-01-23 08:18 UTC, Auldrin-Possa commented
> Morning @Auldrin-Possa, there is a build fail on this branch now. Please could you look into fixing it?

Resolved.

2023-01-23 08:35 UTC, kevwhitt-hee approved these changes

2023-01-23 11:10 UTC, martinfoster-hee commented on DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
>                  );
Super-pedantic but personally I'd have put this as 'delegate user id' so future debuggers know we aren't talking about say an admin user id here. :)

2023-01-23 11:10 UTC, martinfoster-hee reviewed
Looks good to me.

2023-01-23 11:12 UTC, kevwhitt-hee approved these changes

2023-01-23 11:12 UTC, merged