TD-1238:Wire cancel buttons in the super admin Users interface to ret…
TechnologyEnhancedLearning/DLSV2 pull request #1729
Opened 2023-03-28 15:20 UTC by sarathlal-sarangadharan

…urn to the original page/user

### JIRA link
https://hee-tis.atlassian.net/browse/TD-1238

### Description
Wired cancel buttons in the super admin Users interface to return to the original page/user. Changes include below pages
1. Set user password
2. User centre roles
Also verified below pages.
3. Edit user details
4. Inactivate User

### Screenshots
1. **Set user password**
![image](https://user-images.githubusercontent.com/120369940/228283453-9b105aec-49c4-43e0-a801-4cc0385e18cb.png)
on Cancel click
![image](https://user-images.githubusercontent.com/120369940/228283607-003cae73-4f47-4b00-bd73-0b7de4009ea1.png)

2. **User centre roles**
![image](https://user-images.githubusercontent.com/120369940/228282866-f9916028-692d-4e80-8619-5802aae04504.png)
on Cancel click
![image](https://user-images.githubusercontent.com/120369940/228283185-c007f01d-19e1-473b-af79-4302f2c722b9.png)

Also verified below pages.
3. **Edit user details**
![image](https://user-images.githubusercontent.com/120369940/228282153-be03efd4-b74f-49f4-a808-eb8152e9c9a9.png)

on Cancel click
![image](https://user-images.githubusercontent.com/120369940/228282347-26888c6a-8e4b-4371-8c71-e71840e4fd01.png)

4. **Inactivate User**
![image](https://user-images.githubusercontent.com/120369940/228281817-a431c5af-0579-4edc-b272-86f19294e49a.png)
on Cancel click
![image](https://user-images.githubusercontent.com/120369940/228282037-9c54f43b-00ca-408b-bed2-23e6c89474e6.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [x] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

6. Inactivate User
![image](https://user-images.githubusercontent.com/120369940/228281817-a431c5af-0579-4edc-b272-86f19294e49a.png)
After Cancel click
![image](https://user-images.githubusercontent.com/120369940/228282037-9c54f43b-00ca-408b-bed2-23e6c89474e6.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [x] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [x] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

2023-03-29 07:54 UTC, kevwhitt-hee requested changes
This is working well. I wonder if we could add an asp-fragment to these links to scroll the user to the right location on the page? We have a an ID on the spans containing the name that we could include as a URL fragment in the link to achieve this: 
![image](https://user-images.githubusercontent.com/67740339/228464821-59ac5870-2049-418e-93a8-cc582de97d70.png)
An example of this can be seen in: Web\Views\Frameworks\Developer\AddCompetencyLearningResources.cshtml

2023-03-29 09:48 UTC, sarathlal-sarangadharan commented
> This is working well. I wonder if we could add an asp-fragment to these links to scroll the user to the right location on the page? We have a an ID on the spans containing the name that we could include as a URL fragment in the link to achieve this: ![image](https://user-images.githubusercontent.com/67740339/228464821-59ac5870-2049-418e-93a8-cc582de97d70.png) An example of this can be seen in: Web\Views\Frameworks\Developer\AddCompetencyLearningResources.cshtml



> AddCompetencyLearningResources

@kevwhitt-hee Thank you for sharing a reference. Sure, I will work on this.

2023-03-30 08:18 UTC, sarathlal-sarangadharan commented
> > This is working well. I wonder if we could add an asp-fragment to these links to scroll the user to the right location on the page? We have a an ID on the spans containing the name that we could include as a URL fragment in the link to achieve this: ![image](https://user-images.githubusercontent.com/67740339/228464821-59ac5870-2049-418e-93a8-cc582de97d70.png) An example of this can be seen in: Web\Views\Frameworks\Developer\AddCompetencyLearningResources.cshtml
> 
> > AddCompetencyLearningResources
> 
> @kevwhitt-hee Thank you for sharing a reference. Sure, I will work on this.
@kevwhitt-hee Functionality implemented to retain the selected user position in main page on Cancel click. Please review.

![image](https://user-images.githubusercontent.com/120369940/228773834-470a5e41-84b7-44d3-916b-385e9e1f9280.png)

![image](https://user-images.githubusercontent.com/120369940/228773299-6207780d-6d27-430a-bab7-d7d8e48b0d2a.png)

After Cancel click in "View Centre Accounts Role"
![image](https://user-images.githubusercontent.com/120369940/228774097-a60ff53c-5c24-4e49-9175-fdd331b84637.png)

2023-03-30 15:03 UTC, kevwhitt-hee approved these changes

2023-03-30 15:04 UTC, merged