TD-997:Super Admin - User Accounts - Set password view_user name issu…
TechnologyEnhancedLearning/DLSV2 pull request #1748
Opened 2023-04-03 14:07 UTC by sarathlal-sarangadharan

### JIRA link
https://hee-tis.atlassian.net/browse/TD-997

### Description
When no Password entered and clicked Submit, User name values are not displayed and it is blank 

### Screenshots
**Before issue fix:**
![image](https://user-images.githubusercontent.com/120369940/229532778-78daa09d-f560-4114-b3b9-7fff3ccebd7d.png)

**After code fix**
![image](https://user-images.githubusercontent.com/120369940/229533403-51e982cb-711c-4e51-a91d-c05d1a084816.png)
![image](https://user-images.githubusercontent.com/120369940/229533787-c30947de-e528-4243-90d5-3b1b4b37ce87.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

2023-04-03 15:25 UTC, martinfoster-hee reviewed
Looks good.

2023-04-04 06:45 UTC, kevwhitt-hee commented on DigitalLearningSolutions.Web/Controllers/SuperAdmin/Users/SuperAdminUserSetPasswordController.cs
> +            TempData.Keep();
We should add the username to the formData (and submit from a hidden field) rather than using a cookie to store it, I think?

2023-04-04 06:46 UTC, kevwhitt-hee requested changes
See suggested change in code. We should only use cookies when we have to.

2023-04-05 07:16 UTC, kevwhitt-hee reviewed
Please see query re possible redundant code line.

2023-04-05 07:30 UTC, merged