TD-1220:Fixes to SelfAssessmentResults table usage
TechnologyEnhancedLearning/DLSV2 pull request #1766
Opened 2023-04-11 13:08 UTC by sarathlal-sarangadharan

### JIRA link
https://hee-tis.atlassian.net/browse/TD-1220

### Description
1. Created history table **_SelfAssessmentResultSupervisorVerificationsHistory_** for  **_SelfAssessmentResultSupervisorVerifications_**
2. Deleted multiple records from tables **_SelfAssessmentResults_** & SelfAssessmentResultSupervisorVerifications
3. Created a Unique constraint to the **_SelfAssessmentResults_** table on DelegateUserID, CompetencyID, AssessmentQuestionID
4. Altered queries used logic to get latest record from  SelfAssessmentResults table.

### Screenshots
**_Before code changes:_**
![image](https://user-images.githubusercontent.com/120369940/231141675-b7f48c6e-6e02-499f-8aae-f384c4c176c6.png)
![image](https://user-images.githubusercontent.com/120369940/231141898-d4bf7cef-a23e-4785-8acc-84fbdd5f4a2f.png)
![image](https://user-images.githubusercontent.com/120369940/231141985-98d276d6-2858-42e8-b9bf-40c9efccd049.png)
![image](https://user-images.githubusercontent.com/120369940/231142063-e9ccb59e-2922-442b-a4c1-5a1f7b14c732.png)

**_After code changes:_**
SelfAssessmentResultSupervisorVerifications table changes:
![image](https://user-images.githubusercontent.com/120369940/231142612-8e3ac8be-1e0b-46d3-8aa7-8b10e3637a51.png)

**SelfAssessmentResults table changes**
![image](https://user-images.githubusercontent.com/120369940/231143119-9e412cfe-880b-418f-850a-85e66deb1fdc.png)

**Deleted duplicate records**
![image](https://user-images.githubusercontent.com/120369940/231143264-cf73584d-5110-48b3-a6a8-23e8450c2662.png)

**submit changes:**
![image](https://user-images.githubusercontent.com/120369940/231143701-c612e382-c9e4-4ae5-98ac-e0643f7ebabf.png)

**select data count :**
![image](https://user-images.githubusercontent.com/120369940/231145928-405dfa6d-8945-4123-8802-dfcc69f1117e.png)

**SelfAssessmentReportDartaService**
![image](https://user-images.githubusercontent.com/120369940/231170641-6dca89bb-72b2-4af1-b163-5e41471b7ed5.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [x] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

2023-04-12 10:08 UTC, sarathlal-sarangadharan commented
> @sarathlal-sarangadharan, I was expecting the system versioning to be switched on before we delete the SelfAssessmentResultSupervisorVerifications records so that we don't lose the record of them. Will this work?

Hi @kevwhitt-hee  , I tried this already. But was getting below error when we use system versioning before data delete.
![image](https://user-images.githubusercontent.com/120369940/231426501-c8e11f90-29eb-4b38-b4a8-bdcdef1f7190.png)

Will check this again and update you.

2023-04-12 12:51 UTC, kevwhitt-hee commented
> > @sarathlal-sarangadharan, I was expecting the system versioning to be switched on before we delete the SelfAssessmentResultSupervisorVerifications records so that we don't lose the record of them. Will this work?
> 
> Hi @kevwhitt-hee , I tried this already. But was getting below error when we use system versioning before data delete. ![image](https://user-images.githubusercontent.com/120369940/231426501-c8e11f90-29eb-4b38-b4a8-bdcdef1f7190.png)
> 
> Will check this again and update you.

Looks like we need to add begin / end transactions to the steps - https://dba.stackexchange.com/questions/211467/error-updating-temporal-tables?

2023-04-12 17:38 UTC, sarathlal-sarangadharan commented
> > > @sarathlal-sarangadharan, I was expecting the system versioning to be switched on before we delete the SelfAssessmentResultSupervisorVerifications records so that we don't lose the record of them. Will this work?
> > 
> > 
> > Hi @kevwhitt-hee , I tried this already. But was getting below error when we use system versioning before data delete. ![image](https://user-images.githubusercontent.com/120369940/231426501-c8e11f90-29eb-4b38-b4a8-bdcdef1f7190.png)
> > Will check this again and update you.
> 
> Looks like we need to add begin / end transactions to the steps - https://dba.stackexchange.com/questions/211467/error-updating-temporal-tables?

Hi @kevwhitt-hee ,Getting error after using Begin/end transaction. Seems like we need to build exception handling to retry till the transaction is successful. Working on it.

2023-04-12 18:00 UTC, sarathlal-sarangadharan commented
> > > > @sarathlal-sarangadharan, I was expecting the system versioning to be switched on before we delete the SelfAssessmentResultSupervisorVerifications records so that we don't lose the record of them. Will this work?
> > > 
> > > 
> > > Hi @kevwhitt-hee , I tried this already. But was getting below error when we use system versioning before data delete. ![image](https://user-images.githubusercontent.com/120369940/231426501-c8e11f90-29eb-4b38-b4a8-bdcdef1f7190.png)
> > > Will check this again and update you.
> > 
> > 
> > Looks like we need to add begin / end transactions to the steps - https://dba.stackexchange.com/questions/211467/error-updating-temporal-tables?
> 
> Hi @kevwhitt-hee ,Getting error after using Begin/end transaction. Seems like we need to build exception handling to retry till the transaction is successful. Working on it.

Hi @kevwhitt-hee , I separated the logics to different classes now. Please review and share your thought. It is working as expected and deleted records are stored in history table.
![image](https://user-images.githubusercontent.com/120369940/231543844-6d14a331-8d2a-4aeb-b37f-07131f4feaad.png)

2023-04-13 13:05 UTC, kevwhitt-hee commented
Approved but I'm going to check out the branch and test before merging. Thanks @sarathlal-sarangadharan

2023-04-14 08:25 UTC, kevwhitt-hee commented
This is looking good, @sarathlal-sarangadharan. There are a few more places where we are retrieving the latest SelfAssessmentResults record where we no longer need to be:

- SupervisorService.cs 
  - GetSelfAssessmentResultSummary - lines 902, 916, 932, 964, 980
  - GetCandidateAssessmentSupervisorVerificationSummaries - line 1031

- CandidateAssessmentExportDataService.cs
 - GetCandidateAssessmentExportSummary - lines 24, 38, 54, 70, 86, 102

Please could these be updated too?

2023-04-14 11:19 UTC, sarathlal-sarangadharan commented
> This is looking good, @sarathlal-sarangadharan. There are a few more places where we are retrieving the latest SelfAssessmentResults record where we no longer need to be:
> 
> * SupervisorService.cs
>   
>   * GetSelfAssessmentResultSummary - lines 902, 916, 932, 964, 980
>   * GetCandidateAssessmentSupervisorVerificationSummaries - line 1031
> * CandidateAssessmentExportDataService.cs
> * GetCandidateAssessmentExportSummary - lines 24, 38, 54, 70, 86, 102
> 
> Please could these be updated too?

Hi @kevwhitt-hee ,Sure I will work on this.

2023-04-14 15:24 UTC, kevwhitt-hee requested changes
Noticed a scenario that we need to cope with - 

- Learner submits a self assessment result
- Supervisor confirms result (SelfAssessmentResultSupervisorVerifications record)
- Learner submits a new self assessment result for same and we update it

We need to delete the SelfAssessmentResultSupervisorVerifications associated with the original result.

2023-04-14 15:24 UTC, kevwhitt-hee commented on DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
> +                            UPDATE SelfAssessmentResults
If we update a `SelfAssessmentResults` record we need to delete any related `SelfAssessmentResultSupervisorVerifications` record.

2023-04-14 17:32 UTC, sarathlal-sarangadharan commented
> > This is looking good, @sarathlal-sarangadharan. There are a few more places where we are retrieving the latest SelfAssessmentResults record where we no longer need to be:
> > 
> > * SupervisorService.cs
> >   
> >   * GetSelfAssessmentResultSummary - lines 902, 916, 932, 964, 980
> >   * GetCandidateAssessmentSupervisorVerificationSummaries - line 1031
> > * CandidateAssessmentExportDataService.cs
> > * GetCandidateAssessmentExportSummary - lines 24, 38, 54, 70, 86, 102
> > 
> > Please could these be updated too?
> 
> Hi @kevwhitt-hee ,Sure I will work on this.

Hi @kevwhitt-hee ,
1. GetSelfAssessmentResultSummary - lines 902, 916, 932, 964, 980
Before code change:
![image](https://user-images.githubusercontent.com/120369940/232084725-a6844198-533c-4b48-a3f4-eb2cb728a9c9.png)

After code change::
![image](https://user-images.githubusercontent.com/120369940/232085050-54f87b61-bb61-43a4-b5d1-a43718176030.png)

2. GetCandidateAssessmentSupervisorVerificationSummaries - line 1031
Before code change:

After code change:
![image](https://user-images.githubusercontent.com/120369940/232115366-e4bfed38-b775-46e1-97b7-f5fe6b4b12a1.png)


3. CandidateAssessmentExportDataService.cs
      GetCandidateAssessmentExportSummary - lines 24, 38, 54, 70, 86, 102

Before code change:
![image](https://user-images.githubusercontent.com/120369940/232114589-2f284191-d343-43d3-9c33-6f2fe2a02bf8.png)

After code change:
![image](https://user-images.githubusercontent.com/120369940/232114656-0ef4a840-5170-4b59-8fbe-b5bb6e45dac0.png)

2023-04-17 09:02 UTC, sarathlal-sarangadharan commented
> * Learner submits a self assessment result
> * Supervisor confirms result (SelfAssessmentResultSupervisorVerifications record)
> * Learner submits a new self assessment result for same and we update i

@kevwhitt-hee  Working on this scenario. Will connect you for any doubt.

2023-04-17 14:38 UTC, kevwhitt-hee requested changes
I don't think we are limiting the join to SelfAssessmentResults enough in this query. See code comments.

2023-04-17 14:38 UTC, kevwhitt-hee commented on DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs
> +                              CompetencyAssessmentQuestions AS caq1 ON sas1.CompetencyID = caq1.CompetencyID ON sar1.SelfAssessmentID =sas1.SelfAssessmentID and sar1.CompetencyID=sas1.CompetencyID LE
and again

2023-04-17 14:38 UTC, kevwhitt-hee commented on DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs
> +                              CompetencyAssessmentQuestions AS caq1 ON sas1.CompetencyID = caq1.CompetencyID ON sar1.SelfAssessmentID =sas1.SelfAssessmentID and sar1.CompetencyID=sas1.CompetencyID LE
and again

2023-04-17 15:54 UTC, sarathlal-sarangadharan commented
> I don't think we are limiting the join to SelfAssessmentResults enough in this query. See code comments.

Hi @kevwhitt-hee , Amended the query . Please review and also please find test evidences. Now count matches with old query.

Original query result:
![image](https://user-images.githubusercontent.com/120369940/232533602-03b460cf-fb0f-4479-8482-f7b9c57ad7dc.png)

Latest query result:
![image](https://user-images.githubusercontent.com/120369940/232533805-322c3dda-b4b5-47d4-8fe8-4bca746a84cb.png)

SupervisorService.cs
Original query result:
![image](https://user-images.githubusercontent.com/120369940/232537173-c2f781cd-4589-41d5-81db-2fd1b8dd63b7.png)

Latest query result:
![image](https://user-images.githubusercontent.com/120369940/232537324-4354e2b9-91fb-4e2d-8006-f6709bc41070.png)

2023-04-19 11:35 UTC, closed without merging