TD-1116 User feedback mechanism.
TechnologyEnhancedLearning/DLSV2 pull request #1793
Opened 2023-04-18 09:48 UTC by martinfoster-hee

### JIRA link
_DLSV2-XXXX_

### Description
_Describe what has changed and how that will affect the app. If relevant, add references to the resources you used. Use this as your opportunity to highlight anything odd and give people context around particular decisions._

### Screenshots
_Attach screenshots on mobile, tablet and desktop._

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

2023-05-26 07:28 UTC, kevwhitt-hee commented
This is looking very good, indeed Martin. Building and running it, I saw just one problem with the label of the "Back to" button (it did redirect me back to where I came from - the Learning Portal -> Current Activities view):

![image](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/67740339/1f76730d-87a9-4d2d-99d8-7c173b3cbbbd)

2023-05-26 07:35 UTC, rshrirohit requested changes

2023-05-26 07:54 UTC, martinfoster-hee commented on DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml
> +        @if ((bool?)ViewData[LayoutViewDataKeys.DoNotDisplayUserFeedbackBar] != true)
Good call.

2023-05-26 07:54 UTC, martinfoster-hee commented
> caching

Ah, good idea!

2023-05-30 09:53 UTC, martinfoster-hee commented on DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml
> +        @if ((bool?)ViewData[LayoutViewDataKeys.DoNotDisplayUserFeedbackBar] != true)
Done.

2023-06-05 10:33 UTC, merged