TD-1577: The "Change" link will be hidden when there is only one centre and when  supervisors enrolling a delegate on a self assessment can only do so in the “Educator manager”
TechnologyEnhancedLearning/DLSV2 pull request #1953
Opened 2023-06-12 16:01 UTC by sarathlal-sarangadharan

### JIRA link
https://hee-tis.atlassian.net/browse/TD-1577

### Description
1. “The "Change" link should be hidden when there is only one centre“
2. Roles selection has been be limited in the Supervise path

### Screenshots
Before code change:
![image](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/120369940/70f45c94-c2cd-4ae1-a6e2-042596b6a65d)
![image](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/120369940/27e9b6fa-0f06-4797-9f15-dcac7c0cbf76)
![image](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/120369940/6f9f3062-c978-40f3-bd65-66d108b1573d)

After code change:
![image](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/120369940/baa5d150-b974-4c55-85d8-c42725aa93db)
![image](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/120369940/fb1cf067-19cc-4948-8fa8-7ddf0ff3447d)

**Change functionality when number of centre > 1** 

Before code change:

After code change:
![image](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/120369940/51e1fe6d-ff55-42c9-97ef-87e3717be69a)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

2023-06-13 07:22 UTC, kevwhitt-hee requested changes
It looks like we have removed the logic to check if more than one role is available and display the choose role step if there is. None of the existing self assessments have multiple roles available but that may change in future.

Also, I can see the same logic in the `QuickAddSupervisor` controller action - does this need the same updates too?

2023-06-13 10:56 UTC, sarathlal-sarangadharan commented
> It looks like we have removed the logic to check if more than one role is available and display the choose role step if there is. None of the existing self assessments have multiple roles available but that may change in future.
> 
> Also, I can see the same logic in the `QuickAddSupervisor` controller action - does this need the same updates too?

Hi @kevwhitt-hee , It looks we have multiple roles available for a self assessment in local DB as well as in UAT. Please find below screenshot.

Local DB:
![image](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/120369940/566f438a-2de0-4b28-a741-e23d862ae946)
UAT DB:
![image](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/120369940/184eace9-239a-445a-9ade-82b43fc060aa)

If we include the logic to check more than one role, again we will get the role selection page. Please correct me if I am wrong.

2023-06-14 15:59 UTC, sarathlal-sarangadharan commented
> It looks like we have removed the logic to check if more than one role is available and display the choose role step if there is. None of the existing self assessments have multiple roles available but that may change in future.
> 
> Also, I can see the same logic in the `QuickAddSupervisor` controller action - does this need the same updates too?

Hi @kevwhitt-hee , This action `QuickAddSupervisor`  is being called from role selection page which is not using at the moment. When there is a role selection in future, the functionality will continue working as it is.

2023-06-15 07:11 UTC, kevwhitt-hee approved these changes

2023-06-15 07:14 UTC, merged