TD-2371 Fixed space showing instead of graph for short date range when 'view more' link is not visible and also fixed in Course usage screen
TechnologyEnhancedLearning/DLSV2 pull request #2118
Opened 2023-09-06 13:54 UTC by manishagarwalnhs

### JIRA link
https://hee-tis.atlassian.net/browse/TD-2371

### Description
Points addressed in this Commit :
1) Fixed space showing instead of graph for short date range when 'view more' link is not visible and also fixed in Course usage screen by modifying the script and view.

### Screenshots
![Course-usage-Digital-Learning-Solutions](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/866a9ebf-a759-41d9-83db-32b69e884b1c)
![WavePlugin](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/8e49a775-8d46-432e-998a-0f0d8d58ebb5)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

2023-09-07 12:07 UTC, manishagarwalnhs commented on DigitalLearningSolutions.Web/Scripts/superAdmin/platformreports.ts
The file, SelfAssessmentsReport.cshtml uses platformreports.js reference but since the ts file is missing, the js file is not created via mapping. The ts file includes all the logic for charts. One solution could be to include the reports.ts file directly in SelfAssessmentsReport.cshtml but this file already had a reference to platformreports.js so I created a new ts file for the js.

2023-09-11 07:38 UTC, kevwhitt-hee commented on DigitalLearningSolutions.Web/Scripts/superAdmin/platformreports.ts
If you update your branch from master, I don't think that is the case any longer, @manishagarwalnhs. platformreports.ts is now split into courseReports.ts and selfAssessmentReports.ts. SelfAssessmentsReport.cshtml now references the latter.

2023-09-11 07:39 UTC, kevwhitt-hee requested changes
This branch is stale and needs updating from master.

2023-09-12 06:40 UTC, kevwhitt-hee approved these changes
I've removed a reference to the platformreports.ts file from the CS project file and this is now ready to merge.

2023-09-12 07:26 UTC, merged