Fixes super admin link not working in dev
TechnologyEnhancedLearning/DLSV2 pull request #2603
Opened 2024-04-12 10:31 UTC by kevwhitt-hee

### JIRA link
N/A

### Description
Small tweak to fix the broken dev code on the Release .29 branch

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [x] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

2024-04-12 10:32 UTC, kevwhitt-hee commented
Hi Rohit. Proposing this as a fix for the broken dev code in the R.29 branch in case you are still looking for a fix.

2024-04-15 06:42 UTC, rshrirohit commented
I think this PR contains some changes related to TD-3835 (https://github.com/TechnologyEnhancedLearning/DLSV2/pull/2602/files) that are not intended here. Could you please have a look?

2024-04-15 06:48 UTC, rshrirohit requested changes

2024-04-15 06:48 UTC, rshrirohit commented on DigitalLearningSolutions.Web/Models/Enums/UserCard.cs
> +    public enum UserCard
I think this is the only change required to make the Super Admin work again. I tried this in my local and it works. The certificates however are still not working in my local. Let me try to figure a fix for certificates as well, and then we can push another commit in the same PR.

2024-04-15 10:40 UTC, closed without merging