Heedls 418 administrator edit details
TechnologyEnhancedLearning/DLSV2 pull request #529
Opened 2021-08-03 13:01 UTC by AlexJacksonDS

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-418

### Description
Adds a new page to edit admin roles, making use of new checkboxes and radios view components. There are still some outstanding questions about permissions for the page to be resolved since the requirements seem to state this page is accessible to more people than its parent page. Have implemented with the same access for now.

### Screenshots
![image](https://user-images.githubusercontent.com/59561751/128019565-5cb2337e-84b7-4059-8509-f203327dea67.png)
![image](https://user-images.githubusercontent.com/59561751/128019629-b0634304-64eb-464c-b299-68e85198f94d.png)
![image](https://user-images.githubusercontent.com/59561751/128019658-21e67a95-c143-4814-aa59-97f5bc852496.png)

-----
### Developer checks
I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (controller, data services, services, view models etc) and manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme.
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2021-08-04 14:05 UTC, livzorn approved these changes
No issues that I can find!

2021-08-05 21:00 UTC, ibrahimmunir14 requested changes

2021-08-06 13:00 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/EditRolesViewModel.cs
> +            ),
I think it's more confusing to have improperly named properties/parameters, and properties we would never use the value of (Value would always be overwritten in the view component logic). Maybe I could move one of them from the namespace?

I can't make CheckboxesItemViewModel private like that, it needs to be accessed from both the view component Invoke and the model. I don't think the logic in the Invoke can be moved to the constructor of the CheckboxesItemViewModel in a sensible way.

2021-08-06 13:09 UTC, AlexJacksonDS commented
Not really sure what I can do about the page structure issues you've raised. The fieldset labels match the NHS styling for the respective components. So does the dropdown.

They need to have labels, so the only real solution would be to have duplicate headers and make the label smaller than the NHS components:
![image](https://user-images.githubusercontent.com/59561751/128515034-80fed7f1-3cdf-4460-b8e0-56ab01a79952.png)

2021-08-06 13:24 UTC, ibrahimmunir14 commented
> Not really sure what I can do about the page structure issues you've raised. The fieldset labels match the NHS styling for the respective components. So does the dropdown.
> 
> They need to have labels, so the only real solution would be to have duplicate headers and make the label smaller than the NHS components:

Ah. Well, to me this makes more sense structurally but duplicate headers look bad. Can we ask HEE?

2021-08-06 13:26 UTC, AlexJacksonDS commented
> Ah. Well, to me this makes more sense structurally but duplicate headers look bad. Can we ask HEE?

I'll do it on Monday when everyone is back

2021-08-09 10:53 UTC, AlexJacksonDS commented
Confirmed page structure changes with Kevin, updated the screenshots in the description.

2021-08-09 14:24 UTC, ibrahimmunir14 approved these changes
LGTM

2021-08-09 14:27 UTC, merged