Heedls 541c edit filters again
TechnologyEnhancedLearning/DLSV2 pull request #576
Opened 2021-09-03 16:20 UTC by JBsoftwire

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-541

### Description
This is the frontend component for the edit filters page for HEEDLS-541. It has some backend changes to populate the select lists, but no logic to handle actually sending a filter edit request, which will be dealt with in a future review.

### Screenshots
![image](https://user-images.githubusercontent.com/34240850/132033997-35177074-a3fe-4ecf-afab-471ada3dcf8c.png)
![image](https://user-images.githubusercontent.com/34240850/132037506-59135b0a-02c2-4cc8-b93a-a618d2c7386c.png)

-----
### Developer checks
I have:
- [X] Run the formatter and made sure there are no IDE errors.
- [X] Written tests for the changes (controller, data services, services, view models etc) and manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [X] Updated/added documentation in Swiki and/or Readme.
- [X] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [X] Scanned over my own MR to ensure everything is as expected.

2021-09-03 16:23 UTC, JBsoftwire commented on DigitalLearningSolutions.Web/ViewComponents/SelectListViewComponent.cs
> +            var selectListViewModel = new SelectListViewModel(
Not related to my ticket, but I thought I should fix this in passing.

2021-09-07 19:04 UTC, ibrahimmunir14 requested changes

2021-09-08 09:15 UTC, JBsoftwire commented on DigitalLearningSolutions.Data/Models/Courses/CourseNameInfo.cs
> +        public int CustomisationId { get; set; }
Holdover from before the 'Course' object was introduced, whoops.

2021-09-08 09:42 UTC, JBsoftwire commented on DigitalLearningSolutions.Web/Views/Shared/Components/DateRangeInput/Default.cshtml
> +    @if (Model.EndDateCheckbox != null) {
It is for this, but I wanted to leave in the option of not including it for the generic component. However this does require updating the view model.

2021-09-09 09:51 UTC, JBsoftwire commented
Added 'from' to start date after demo feedback.
![image](https://user-images.githubusercontent.com/34240850/132664126-dc4e6035-62cb-4134-ad73-89e1669f4834.png)
![image](https://user-images.githubusercontent.com/34240850/132664322-40f7b384-e6ed-4643-a92d-38ccc4c5693f.png)

2021-09-13 08:56 UTC, closed without merging