Heedls 499 deactivate delegate
TechnologyEnhancedLearning/DLSV2 pull request #621
Opened 2021-09-22 11:55 UTC by JBsoftwire

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-499

### Description
The deactivate button on the view delegate page now deactivates the delegate account in question and refreshes the page.

### Screenshots
No visual changes.

-----
### Developer checks
I have:
- [X] Run the formatter and made sure there are no IDE errors.
- [X] Written tests for the changes (controller, data services, services, view models etc) and manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [] Updated/added documentation in Swiki and/or Readme.
- [] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [X] Scanned over my own MR to ensure everything is as expected.

2021-09-22 14:36 UTC, AlexJacksonDS requested changes
Just a couple of minor formatting issues.

2021-09-22 14:36 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
> +        void DeactivateDelegateUser(int delegateId);
Can you move this up next to the other methods in the DelegateUserDataService file?

2021-09-22 14:36 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml
> +          <a class="nhsuk-button delete-button view-delegate-button" role="button" asp-controller="ViewDelegate" asp-action="DeactivateDelegate" asp-route-delegateId="@Model.DelegateInfo.Id">
This line is quite long, can you break it down.

2021-09-22 15:26 UTC, AlexJacksonDS approved these changes

2021-09-22 16:23 UTC, stellake commented on DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs
> +        public IActionResult DeactivateDelegate(int delegateId)
Given that we don't have a confirmation page for the delegates, should we make this POST?

Also, should we add a few controller test (no delegate user, wrong centre and default cases)?

2021-09-23 15:12 UTC, stellake commented on DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/ViewDelegateControllerTests.cs
> +            viewDelegateController = new ViewDelegateController(userDataService, centreCustomPromptsHelper, courseService, passwordResetService)
Nice tests! Do we need all this setup though (e.g. the MockTempData, and could HTTPContext potentially be defaultcontext)?

2021-09-23 15:12 UTC, stellake commented on DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs
> +        [HttpPost]
Do we also need to change the button in the view?

2021-09-24 08:50 UTC, stellake approved these changes
Looks good! 👍

2021-09-24 08:52 UTC, merged