HEEDLS-556 - fix bugs in limit admin roles processing
TechnologyEnhancedLearning/DLSV2 pull request #640
Opened 2021-09-28 09:44 UTC by DanBloxham-sw

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-556

### Description
Fixed the two bugs mentioned in the ticket.
The first (not being added/removed from group) was due to the group labels stored in the DB containing the prompt name for the example tested. The fix for this involves grabbing the prompt name and adding it to the answer given if the answer alone does not match the group label.
The second (progress record not being removed) was due to GroupDelegateRecords being deleted before they had a chance to be used in the RemoveProgress... query. Swapping the order in which these are performed resolves this.

### Screenshots
N/A

-----
### Developer checks
I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (controller, data services, services, view models etc) and manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme.
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2021-09-29 10:44 UTC, JBsoftwire approved these changes
This looks good to me, going to look at the other one now.

edit: after all that fuss at standup, I realised I managed to misread the number of this review and thought it was paired with the other one. Sorry for any confusion!

2021-10-01 09:56 UTC, SteveJacksonSoft requested changes
Very nice, just one question about nullability.

2021-10-01 09:56 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data/Models/LinkedFieldChange.cs
> +        public string? LinkedFieldName { get; set; }
Can this ever be null?

2021-10-05 13:17 UTC, DanBloxham-sw commented on DigitalLearningSolutions.Data/Models/LinkedFieldChange.cs
> +        public string? LinkedFieldName { get; set; }
Good spot. Removed nullability.

2021-10-05 13:22 UTC, SteveJacksonSoft approved these changes
Nice, merge away.

2021-10-05 14:18 UTC, merged