Heedls 408: Fix change password bug introduced in previous HEEDLS-408 work
TechnologyEnhancedLearning/DLSV2 pull request #806
Opened 2021-12-08 17:59 UTC by SteveJacksonSoft

### JIRA link
[_HEEDLS-408_](https://softwiretech.atlassian.net/browse/HEEDLS-408)

### Description
A type handler was added in the original HEEDLS-408 work which overrode how Dapper works with parameters of type `IEnumerable<int>`. This broke change-password.
I've replaced the type handler with a parse in the constructor of `Objective`.

I've also added a couple of tests and made the `ObjectiveBase` class abstract, since we aren't instantiating it and I don't expect we ever will.

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2021-12-08 18:00 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data.Tests/DataServices/PasswordDataServiceTests.cs
> +        private void GivenDelegateUserIsInDatabase(DelegateUser user)
I should pull this out into a test helper.

2021-12-09 11:00 UTC, JBsoftwire requested changes

2021-12-09 11:00 UTC, JBsoftwire commented on DigitalLearningSolutions.Data.Tests/DataServices/PasswordDataServiceTests.cs
> +                .Be(PasswordHashNotYetInDb);
Doesn't this also need an assert for the new delegate?

2021-12-10 11:20 UTC, JBsoftwire approved these changes
Looks good

2021-12-10 14:05 UTC, AlexJacksonDS requested changes
Just a couple of minor things

2021-12-10 16:24 UTC, kevwhitt-hee commented on DigitalLearningSolutions.Data/Models/Tracker/Objective.cs
> +                           new List<int>();
Great news!

2021-12-10 16:26 UTC, kevwhitt-hee approved these changes
Looks good to me.

2021-12-14 09:12 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data.Tests/DataServices/PasswordDataServiceTests.cs
> +        private SqlConnection? connection;
@AlexJacksonDS What are we doing with the other things we're setting up?

2021-12-14 09:14 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Data.Tests/DataServices/PasswordDataServiceTests.cs
> +        private SqlConnection? connection;
e.g. `private PasswordDataService passwordDataService = null!;`

2021-12-14 09:20 UTC, AlexJacksonDS approved these changes

2021-12-14 09:30 UTC, merged