HEEDLS-409 expand boolean parse options for ObjectiveCcArray
TechnologyEnhancedLearning/DLSV2 pull request #812
Opened 2021-12-09 15:00 UTC by JBsoftwire

### JIRA link
[_HEEDLS-409_](https://softwiretech.atlassian.net/browse/HEEDLS-409)

### Description
The endpoint needs to interpret various strings (numerical 1 and 0 as well as 'true' and 'false') as booleans. I've added a special handler in the tracker service to do this, and relevant tests.

### Screenshots
N/A

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2021-12-10 11:00 UTC, DanBloxham-sw requested changes
Could do with an extra unit test. Think there was a typo in the accepted int strings.

2021-12-10 11:28 UTC, DanBloxham-sw approved these changes
I think this is good now.

2021-12-17 15:04 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data/Services/TrackerService.cs
> +        private bool? ConvertToNullableBoolean(string? value)
The way this converts strings to booleans is quite specific to tracker endpoint query params. Could be worth making that slightly more explicit in the title. E.g. Convert*Param*ToNullableBoolean.

2021-12-17 17:18 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data.Tests/Services/TrackerServiceTests.cs
> +        [TestCase("false", false)]
Bah, missed this. We don't have a "False" case, so we may as well add that in. You can merge without rereview after that though.

2021-12-17 17:47 UTC, merged

2021-12-17 17:47 UTC, SteveJacksonSoft approved these changes