HEEDLS-626 Add variable result count to Centre Course Setup
TechnologyEnhancedLearning/DLSV2 pull request #902
Opened 2022-01-31 16:28 UTC by AlexJacksonDS

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-626

### Description
Add custom items per page to the Centre Course Setup page

### Screenshots
![image](https://user-images.githubusercontent.com/59561751/151832303-ab0b9627-95be-4c90-be3f-365c86e9ad50.png)
![image](https://user-images.githubusercontent.com/59561751/151832333-623d1acf-bea3-4aa5-bf01-215475ea110e.png)

![image](https://user-images.githubusercontent.com/59561751/151832390-7fe28829-cc63-49a3-84c7-d2e6811b2daf.png)
![image](https://user-images.githubusercontent.com/59561751/151832461-2c68f83a-48b5-4c73-91bc-5014f58d3970.png)

![image](https://user-images.githubusercontent.com/59561751/151832513-552d97b0-7bd2-4fe8-9a69-0b162295a046.png)
![image](https://user-images.githubusercontent.com/59561751/151832561-731108c1-a03f-48df-91f3-6cec2fbfa032.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2022-01-31 16:59 UTC, livzorn approved these changes
Just one small nitpick, otherwise looks good! No need for rereview

2022-01-31 16:59 UTC, livzorn commented on DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CourseSetup/CourseSetupViewModelTests.cs
> +        public void CourseSetupViewModel_with_custom_items_per_page_should_to_return_the_specified_number_of_delegates()
I think a small typo in this test name

2022-01-31 17:01 UTC, livzorn commented on DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CourseSetup/CourseSetupViewModelTests.cs
> +        public void CourseSetupViewModel_with_custom_items_per_page_should_to_return_the_specified_number_of_delegates()
Oh wait maybe "should to" is a British thing?

2022-02-01 10:18 UTC, DanBloxham-sw requested changes
Very minor clean up change.

2022-02-01 10:18 UTC, DanBloxham-sw commented on DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseSetupViewModel.cs
> +        ) : base(searchString, page, true, sortBy, sortDirection, filterBy, itemsPerPage ?? DefaultItemsPerPage, searchLabel: "Search courses")
Minor, but the "searchLabel: " key is now redundant and can be safely removed.

2022-02-01 10:51 UTC, DanBloxham-sw approved these changes

2022-02-01 11:57 UTC, merged