Heedls 564 set active filter as default
TechnologyEnhancedLearning/DLSV2 pull request #916
Opened 2022-02-07 10:44 UTC by wilkinsm

### JIRA link
[https://softwiretech.atlassian.net/browse/HEEDLS-564](https://softwiretech.atlassian.net/browse/HEEDLS-564)

### Description

- Set the "Active Status" filter to on and "true" by default
- Add sort by Delegate ID to the sorting options.

### Screenshots
![image](https://user-images.githubusercontent.com/18046982/152773181-ce80ab10-239c-4817-a3be-f72f9f77e16a.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2022-02-07 10:46 UTC, wilkinsm commented on DigitalLearningSolutions.Web/Helpers/GenericSortingHelper.cs
> +            "Delegate ID",
Confirmed by KW on 7th Feb, that it should say "Delegate ID" for this candidate number option.

2022-02-08 08:16 UTC, DanBloxham-sw approved these changes
I think this is pretty much perfect.

2022-02-08 15:00 UTC, SteveJacksonSoft requested changes
Yep, just a suggested name change.

2022-02-08 16:36 UTC, wilkinsm commented on DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/sort.ts
> +      return getElementText(searchableElement, 'candidate-number').toLocaleLowerCase();
Done

2022-02-10 15:35 UTC, merged