HEEDLS-649 - make delegate progress field names consistent
TechnologyEnhancedLearning/DLSV2 pull request #956
Opened 2022-02-21 09:36 UTC by DanBloxham-sw

### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-649

### Description
Made changes to the Course Delegates cards, the View Delegate course cards, and the Delegate Progress page to make the names and display of various fields consistent. I'll comment on 567's PR to make sure the Detailed Progress page also has consistent names where appropriate.

### Screenshots
Delegate progress page:
![Delegate Progress](https://user-images.githubusercontent.com/80777689/154927977-a6bc0a5a-3620-4af8-8672-9b80bb058ba0.png)

View delegate course card:
![View Delegate cropped](https://user-images.githubusercontent.com/80777689/154927982-d81fb8a3-1ba8-4cde-a08d-a57783fda28b.png)

Course delegate card:
![Course delegate card](https://user-images.githubusercontent.com/80777689/154927984-9c5480da-eb59-4e53-b232-33ae209a557d.PNG)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ ] Scanned over my own MR to ensure everything is as expected.

2022-02-21 10:06 UTC, AlexJacksonDS requested changes
Just one comment on a potential missed string

2022-02-21 15:24 UTC, GeorgeBlackwell commented
Looks good! Just the one string Alex raised as a protentional change

2022-02-21 15:25 UTC, GeorgeBlackwell approved these changes
Looks good! Just the one string Alex raised as a protentional change

2022-02-23 10:32 UTC, DanBloxham-sw commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditCompletionDate.cshtml
> +    $"For example, {exampleDate.Day} {exampleDate.Month} {exampleDate.Year}. Leave the boxes blank to clear the completion date",
Good spot, changed it.

2022-02-23 10:34 UTC, DanBloxham-sw commented
A question remains about the diagnostic score display when null https://github.com/TechnologyEnhancedLearning/DLSV2/pull/942#discussion_r812636940

2022-02-23 12:28 UTC, merged