Move ConfigHelper to the data project
TechnologyEnhancedLearning/DLSV2 pull request #980
Opened 2022-03-01 16:33 UTC by GeorgeBlackwell

### JIRA link
_[HEEDLS-609](https://softwiretech.atlassian.net/browse/HEEDLS-609)_

### Description
_A technical debt ticket to move `ConfigHelper` to the data project_

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [X] Run the formatter and made sure there are no IDE errors.
- [X] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [X] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [X] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [X] Scanned over my own MR to ensure everything is as expected.

2022-03-02 13:39 UTC, AlexJacksonDS requested changes
There are some changes that I think should have been done that are not yet done, and some files are now in the wrong place following the changes.
Also a query about whether we've done the correct thing here for Steve.

2022-03-03 13:40 UTC, JBsoftwire commented
I don't have any new comments to add to what Alex said, just to make sure you deal with the merge conflicts as well.

2022-03-04 15:07 UTC, SteveJacksonSoft commented on DigitalLearningSolutions.Data/Helpers/ConfigurationExtensions.cs
> +        }
That's a fair point, hadn't realised these existed. Putting them in a class dedicated to old system urls would make sense. `OldSystemEndpointHelper`?

2022-03-04 15:51 UTC, GeorgeBlackwell commented on DigitalLearningSolutions.Data/Helpers/ConfigurationExtensions.cs
> +        }
Agreed, @SteveJacksonSoft are you keen for this to be included in this piece of work?

2022-03-07 13:55 UTC, AlexJacksonDS approved these changes
I think this looks good now, you've just still got another merge conflict to resolve since the last merge from master

2022-03-07 15:49 UTC, merged