HEEDLS-805 synchronise groups bugfix
TechnologyEnhancedLearning/DLSV2 pull request #981
Opened 2022-03-01 17:09 UTC by livzorn

### JIRA link
_HEEDLS-805_

### Description
Fixed 2 bugs:
- Changed the group synchronisation process to account for multiple groups created from the same field
- Fixed the capitalisation on 'Job group'

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors.
- [x] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [x] Scanned over my own MR to ensure everything is as expected.

2022-03-03 13:48 UTC, GeorgeBlackwell approved these changes
Nice work 🚀

2022-03-04 10:34 UTC, DanBloxham-sw requested changes
Some very minor points/questions.

2022-03-04 15:32 UTC, livzorn commented on DigitalLearningSolutions.Data/Services/GroupsService.cs
> +                linkedFieldName + " - " + answer,
Good idea, I've added a private method in this file to do that

2022-03-04 15:38 UTC, livzorn commented on DigitalLearningSolutions.Data/Helpers/LinkedFieldHelper.cs
> +                changedLinkedFieldsWithAnswers.Add(new LinkedFieldChange(RegistrationField.JobGroup.LinkedToFieldId, "Job group", oldJobGroup, newJobGroup));
Oh yeah, I first made this change to fix another bug - when generating groups from job groups, the prefix added is "Job group" (to be consistent with the casing we use when displaying 'Job group' around the site), but here it checks for groups prefixed with "Job Group", so job groups with a prefix weren't being synchronised properly. Now that we've decided to treat the names case insensitively it doesn't make any difference at all, but it doesn't hurt to use the consistent casing.

2022-03-04 15:38 UTC, livzorn commented on DigitalLearningSolutions.Data.Tests/Services/GroupServiceTests/GroupsServiceSynchroniseGroupsTests.cs
> +                ).MustHaveHappened();
yep, done :)

2022-03-04 16:06 UTC, merged