updated remove enrolment
TechnologyEnhancedLearning/DLSV2 pull request #984
Opened 2022-03-03 11:43 UTC by GeorgeBlackwell

### JIRA link
_[HEEDLS-796](https://softwiretech.atlassian.net/browse/HEEDLS-796)_

### Description
_Update "All Delegates - Remove course" with correct wording and layout._

### Screenshots
![image](https://user-images.githubusercontent.com/58184056/156558210-63f4e996-d450-4e01-b571-6087cb2f4646.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [X] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [X] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [X] Scanned over my own MR to ensure everything is as expected.

2022-03-03 12:27 UTC, livzorn commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/ConfirmRemoveFromCourse.cshtml
> +    <h2 class="nhsuk-heading-l word-break">Activity: @Model.CourseName</h2>
Comparing the screenshot to other remove confirmation pages on the site, it looks like there's usually a little more margin under the title, which would be good to have here for consistency. I think it often comes from putting the h1 in it's own row - see RemoveGroupCourse.cshtml and RemoveGroupDelegate.cshtml for examples

2022-03-03 12:39 UTC, DanBloxham-sw requested changes
Looks good, I agree with Olivia's comment, and I've left one more about the UI tests.

2022-03-03 12:39 UTC, DanBloxham-sw commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/ConfirmRemoveFromCourse.cshtml
> +    <h1 class="nhsuk-heading-xl nhsuk-u-margin-bottom-3 word-break">Remove enrolment</h1>
Think this page is listed in the automated accessibility tests, and will need that test parameter changing to match this new h1.

2022-03-07 09:19 UTC, DanBloxham-sw approved these changes
Looks good

2022-03-07 10:09 UTC, merged