HEEDLS-800 add emails
TechnologyEnhancedLearning/DLSV2 pull request #995
Opened 2022-03-08 15:12 UTC by JBsoftwire

### JIRA link
_[HEEDLS-800](https://softwiretech.atlassian.net/browse/HEEDLS-800)_

### Description
Added email titles to cards that did not already have emails, made candidate number title elements hidden (so still searchable), and made the means of inclusion of emails in titles consistent (there were two methods in use before).

### Screenshots
![image](https://user-images.githubusercontent.com/34240850/157264200-81743d23-7e7f-4674-8a0b-3dd180dd6d09.png)
![image](https://user-images.githubusercontent.com/34240850/157264133-a6216f39-bc15-4cf5-9d8f-0da02bee7643.png)
![image](https://user-images.githubusercontent.com/34240850/157263586-10794f47-ba49-48af-884d-ff915b6763f7.png)
![image](https://user-images.githubusercontent.com/34240850/157263497-ff523dbf-cfdd-4fbe-a4ee-109150a8778b.png)
![image](https://user-images.githubusercontent.com/34240850/157263432-7f3cefa3-53f2-46a9-80dd-630952efd0e6.png)

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [X] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [X] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [X] Scanned over my own MR to ensure everything is as expected.

2022-03-09 10:33 UTC, DanBloxham-sw requested changes
These changes have introduced an inconsistency in the search and sort on these pages that will need to be dealt with, though I'm not 100% which way we want to go with it.

2022-03-09 10:33 UTC, DanBloxham-sw commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml
> +        <span class="searchable-element-title" name="name">@Model.DelegateInfo.TitleName</span>
The change includes the email in the `searchable-element-title` span, so the JS search and sort will start returning results based on the email, but the non-JS search won't take it into account. From reading the ticket, it feels to me like we just want to change the display without changing the search functionality. Thoughts on this?

Same applies to the `_AddGroupDelegateCard`

2022-03-09 10:59 UTC, AlexJacksonDS requested changes
I agree with Dan + some extra tidying that I think could happen (assuming it doesn't break search functionality)

2022-03-09 10:59 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml
> +        <span class="searchable-element-candidate-number nhsuk-u-visually-hidden">@Model.DelegateInfo.CandidateNumber</span>
I agree with Dan that the change as is causes the search functionality between JS and no JS to diverge. I also think that this visually hidden span can probably be removed in favour of adding the class to the Candidate number display within the card.

This should probably be checked with HEE whether they want searching on the email or not.

2022-03-18 17:39 UTC, JBsoftwire commented
I'm pushing this so people can look at it, but I haven't been able to test the JS search due to problems with `npm run build`. I'll fix that, test this and update as soon as I can.

2022-03-23 11:02 UTC, JBsoftwire commented
There are some UI test errors, I'm looking into them (apparently these don't fail checks).

2022-03-23 11:59 UTC, JBsoftwire commented
UI errors fixed with a new partial (they also revealed a JS search bug).

2022-03-23 13:32 UTC, AlexJacksonDS requested changes
Looks good, just a couple of tiny things to resolve

2022-03-23 13:32 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/_SearchableCourseDelegateCard.cshtml
> +          <dd class="nhsuk-summary-list__value searchable-element-candidate_number" data-name-for-sorting="delegate-id">
candidate_number? Should this be candidate-number?

2022-03-23 13:32 UTC, AlexJacksonDS commented on DigitalLearningSolutions.Web/Helpers/DisplayStringHelper.cs
> +        public static string GetEmailDisplayString(string? email)
Could probably do with a couple of simple unit tests for this

2022-03-23 15:09 UTC, merged